@startuml parsingalgo
scale 5
skinparam conditionStyle InsideDiamond

(А)
note right: Парсинг считанного запроса
if (Некорректный запрос?) then (Да)
  :Состояние = ОШИБКА; <<task>>
  stop
endif
:Нормализация пути; <<task>>
if (Файл не найден?) then (Да)
  :Подготовка ответа 404; <<task>>
  :Состояние = ЗАПИСЬ; <<task>>
  stop
else 
if (Нет прав на чтение?) then (Да)
  :Подготовка ответа 403; <<task>>
  :Состояние = ЗАПИСЬ; <<task>>
  stop
else 
if (Размер файла больше разрешенного?) then (Да)
  :Подготовка ответа 403; <<task>>
  :Состояние = ЗАПИСЬ; <<task>>
  stop
endif
endif
endif
if (Запрос HEAD?) then (Да)
  :Подготовка ответа 200; <<task>>
  :Состояние = ЗАПИСЬ; <<task>>
  stop
else
if (Файл в кэше?) then (Да)
  :Блокировка кэша файла; <<task>>
  :Подготовка ответа 200; <<task>>
  :Состояние = ЗАПИСЬ; <<task>>
  stop
else 
  :Создание буфера в кеше; <<task>>
  :Создание запроса на чтение файла; <<task>>
  :Состояние = ОЖИДАНИЕ ТЕЛА; <<task>>
  stop
endif

@enduml