#include <string.h>
#include <stddef.h>

#define APPLICATION_JSON_CONTENT_TYPE "application/json"
#define APPLICATION_JAVASCRIPT_CONTENT_TYPE "application/javascript"
#define APPLICATION_XML_CONTENT_TYPE "application/xml"
#define APPLICATION_PDF_CONTENT_TYPE "application/pdf"
#define APPLICATION_ZIP_CONTENT_TYPE "application/zip"
#define APPLICATION_OCTET_STREAM_CONTENT_TYPE "application/octet-stream"

#define TEXT_HTML_CONTENT_TYPE "text/html;charset=utf-8"
#define TEXT_CSS_CONTENT_TYPE "text/css"
#define TEXT_PLAIN_CONTENT_TYPE "text/plain"
#define TEXT_CSV_CONTENT_TYPE "text/csv"
#define TEXT_MARKDOWN_CONTENT_TYPE "text/markdown"

#define IMAGE_JPEG_CONTENT_TYPE "image/jpeg"
#define IMAGE_PNG_CONTENT_TYPE "image/png"
#define IMAGE_GIF_CONTENT_TYPE "image/gif"
#define IMAGE_SVG_CONTENT_TYPE "image/svg+xml"
#define IMAGE_ICO_CONTENT_TYPE "image/x-icon"
#define IMAGE_WEBP_CONTENT_TYPE "image/webp"
#define IMAGE_BMP_CONTENT_TYPE "image/bmp"

#define AUDIO_MPEG_CONTENT_TYPE "audio/mpeg"
#define AUDIO_OGG_CONTENT_TYPE "audio/ogg"
#define AUDIO_WAV_CONTENT_TYPE "audio/wav"

#define VIDEO_MP4_CONTENT_TYPE "video/mp4"
#define VIDEO_MPEG_CONTENT_TYPE "video/mpeg"
#define VIDEO_OGG_CONTENT_TYPE "video/ogg"
#define VIDEO_WEBM_CONTENT_TYPE "video/webm"

#define FONT_WOFF_CONTENT_TYPE "font/woff"
#define FONT_WOFF2_CONTENT_TYPE "font/woff2"
#define FONT_TTF_CONTENT_TYPE "font/ttf"
#define FONT_OTF_CONTENT_TYPE "font/otf"

typedef enum {
    CONTENT_TYPE_TEXT_PLAIN,
    CONTENT_TYPE_TEXT_HTML,
    CONTENT_TYPE_TEXT_CSS,
    CONTENT_TYPE_TEXT_CSV,
    CONTENT_TYPE_TEXT_MARKDOWN,
    
    CONTENT_TYPE_IMAGE_PNG,
    CONTENT_TYPE_IMAGE_JPEG,
    CONTENT_TYPE_IMAGE_GIF,
    CONTENT_TYPE_IMAGE_SVG,
    CONTENT_TYPE_IMAGE_ICO,
    CONTENT_TYPE_IMAGE_WEBP,
    CONTENT_TYPE_IMAGE_BMP,
    
    CONTENT_TYPE_APPLICATION_JAVASCRIPT,
    CONTENT_TYPE_APPLICATION_JSON,
    CONTENT_TYPE_APPLICATION_XML,
    CONTENT_TYPE_APPLICATION_PDF,
    CONTENT_TYPE_APPLICATION_ZIP,
    CONTENT_TYPE_APPLICATION_OCTET_STREAM,
    
    CONTENT_TYPE_AUDIO_MPEG,
    CONTENT_TYPE_AUDIO_OGG,
    CONTENT_TYPE_AUDIO_WAV,
    
    CONTENT_TYPE_VIDEO_MP4,
    CONTENT_TYPE_VIDEO_MPEG,
    CONTENT_TYPE_VIDEO_OGG,
    CONTENT_TYPE_VIDEO_WEBM,
    
    CONTENT_TYPE_FONT_WOFF,
    CONTENT_TYPE_FONT_WOFF2,
    CONTENT_TYPE_FONT_TTF,
    CONTENT_TYPE_FONT_OTF,
} ContentType;

typedef struct {
    const char *extension;
    ContentType type;
    const char *mime_string;
} ContentTypeMap;

// Static map definition (extension-based, no hashing in initialization)
static const ContentTypeMap content_type_map[] = {
    // Text & Markup
    {".html", CONTENT_TYPE_TEXT_HTML, TEXT_HTML_CONTENT_TYPE},
    {".htm", CONTENT_TYPE_TEXT_HTML, TEXT_HTML_CONTENT_TYPE},
    {".css", CONTENT_TYPE_TEXT_CSS, TEXT_CSS_CONTENT_TYPE},
    {".txt", CONTENT_TYPE_TEXT_PLAIN, TEXT_PLAIN_CONTENT_TYPE},
    {".csv", CONTENT_TYPE_TEXT_CSV, TEXT_CSV_CONTENT_TYPE},
    {".md", CONTENT_TYPE_TEXT_MARKDOWN, TEXT_MARKDOWN_CONTENT_TYPE},
    
    // Images
    {".png", CONTENT_TYPE_IMAGE_PNG, IMAGE_PNG_CONTENT_TYPE},
    {".jpg", CONTENT_TYPE_IMAGE_JPEG, IMAGE_JPEG_CONTENT_TYPE},
    {".jpeg", CONTENT_TYPE_IMAGE_JPEG, IMAGE_JPEG_CONTENT_TYPE},
    {".gif", CONTENT_TYPE_IMAGE_GIF, IMAGE_GIF_CONTENT_TYPE},
    {".svg", CONTENT_TYPE_IMAGE_SVG, IMAGE_SVG_CONTENT_TYPE},
    {".ico", CONTENT_TYPE_IMAGE_ICO, IMAGE_ICO_CONTENT_TYPE},
    {".webp", CONTENT_TYPE_IMAGE_WEBP, IMAGE_WEBP_CONTENT_TYPE},
    {".bmp", CONTENT_TYPE_IMAGE_BMP, IMAGE_BMP_CONTENT_TYPE},
    {".tiff", CONTENT_TYPE_IMAGE_BMP, IMAGE_BMP_CONTENT_TYPE},
    
    // Scripts & Data
    {".js", CONTENT_TYPE_APPLICATION_JAVASCRIPT, APPLICATION_JAVASCRIPT_CONTENT_TYPE},
    {".mjs", CONTENT_TYPE_APPLICATION_JAVASCRIPT, APPLICATION_JAVASCRIPT_CONTENT_TYPE},
    {".json", CONTENT_TYPE_APPLICATION_JSON, APPLICATION_JSON_CONTENT_TYPE},
    {".xml", CONTENT_TYPE_APPLICATION_XML, APPLICATION_XML_CONTENT_TYPE},
    
    // Documents
    {".pdf", CONTENT_TYPE_APPLICATION_PDF, APPLICATION_PDF_CONTENT_TYPE},
    
    // Archives
    {".zip", CONTENT_TYPE_APPLICATION_ZIP, APPLICATION_ZIP_CONTENT_TYPE},
    {".tar", CONTENT_TYPE_APPLICATION_OCTET_STREAM, APPLICATION_OCTET_STREAM_CONTENT_TYPE},
    {".gz", CONTENT_TYPE_APPLICATION_OCTET_STREAM, APPLICATION_OCTET_STREAM_CONTENT_TYPE},
    
    // Audio
    {".mp3", CONTENT_TYPE_AUDIO_MPEG, AUDIO_MPEG_CONTENT_TYPE},
    {".ogg", CONTENT_TYPE_AUDIO_OGG, AUDIO_OGG_CONTENT_TYPE},
    {".wav", CONTENT_TYPE_AUDIO_WAV, AUDIO_WAV_CONTENT_TYPE},
    {".flac", CONTENT_TYPE_AUDIO_OGG, AUDIO_OGG_CONTENT_TYPE},
    
    // Video
    {".mp4", CONTENT_TYPE_VIDEO_MP4, VIDEO_MP4_CONTENT_TYPE},
    {".mpeg", CONTENT_TYPE_VIDEO_MPEG, VIDEO_MPEG_CONTENT_TYPE},
    {".ogv", CONTENT_TYPE_VIDEO_OGG, VIDEO_OGG_CONTENT_TYPE},
    {".webm", CONTENT_TYPE_VIDEO_WEBM, VIDEO_WEBM_CONTENT_TYPE},
    {".avi", CONTENT_TYPE_VIDEO_MPEG, VIDEO_MPEG_CONTENT_TYPE},
    
    // Fonts
    {".woff", CONTENT_TYPE_FONT_WOFF, FONT_WOFF_CONTENT_TYPE},
    {".woff2", CONTENT_TYPE_FONT_WOFF2, FONT_WOFF2_CONTENT_TYPE},
    {".ttf", CONTENT_TYPE_FONT_TTF, FONT_TTF_CONTENT_TYPE},
    {".otf", CONTENT_TYPE_FONT_OTF, FONT_OTF_CONTENT_TYPE},
    
    // WebAssembly
    {".wasm", CONTENT_TYPE_APPLICATION_OCTET_STREAM, APPLICATION_OCTET_STREAM_CONTENT_TYPE},
};

static const size_t content_type_map_size = sizeof(content_type_map) / sizeof(content_type_map[0]);

ContentType GetContentType(const char *path);

const char *GetContentTypeString(ContentType content_type);

const char *ContentTypeByPath(const char *path);