#ifndef HTTP_ERRORS_H__
#define HTTP_ERRORS_H__

#define ERR_OK 0
#define ERR_HTTP_MEMORY 1
#define ERR_HTTP_PARSE 2
#define ERR_UNSUPPORTED_HTTP_METHOD 3
#define ERR_UNSUPPORTED_HTTP_VERSION 4
#define ERR_REQUEST_NOT_PARSED 5
#define ERR_RESPONSE_NOT_FILLED 6

#define ERR_WORKER_NOT_RUNNING 7
#define ERR_WORKER_ALREADY_RUNNING 8
#define ERR_WORKER_SHUTDOWN 9
#define ERR_WORKER_MEMORY 10
#define ERR_WORKER_MAX_REQUESTS_EXCEEDED 11
#define ERR_WORKER_READ_ERROR 12
#define ERR_WORKER_WRITE_ERROR 13


#define ERR_SERVER_NOT_RUNNING 14
#define ERR_SERVER_ALREADY_RUNNING 15
#define ERR_SERVER_SHUTDOWN 16
#define ERR_SERVER_MEMORY 17


#define ERR_REQUEST_READ_END 18
#define ERR_REQUEST_NONBLOCKED_ERROR 18
#define ERR_REQUEST_READ_ERROR 19

#define ERR_RESPONSE_WRITE_END 20
#define ERR_RESPONSE_NONBLOCKED_ERROR 20
#define ERR_RESPONSE_WRITE_ERROR 21

#endif